# numpy-基本功能
## 簡介
根據 [Numpy 官方網站](https://numpy.org/):

> NumPy is the fundamental package for scientific computing with Python.
> 
> NumPy 是設計用於進行科學計算的 Python 工具
> 
> It contains among other things:
>
> a powerful N-dimensional array object
>
> sophisticated (broadcasting) functions
>
> tools for integrating C/C++ and Fortran code
>
> useful linear algebra, Fourier transform, and random number capabilities
>
> Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
> Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide
> variety of databases.



## 教學目標
這份教學的目標是介紹基本的 numpy 功能，並學習快速操作大量數值型態的資料。

## 適用對象
適用於有程式基礎，且擁有 python 基礎的人。

## 大綱
- [一維陣列](#一維陣列)
- [陣列運算](#陣列運算)
- [數值型態](#數值型態)
- [二維陣列](#二維陣列)
- [高維陣列](#高維陣列)

## 執行方法
在 Jupyter notebook 中，選取想要執行的區塊後，使用以下其中一種方法執行
- 上方工具列中，按下 `Cell` &lt; `Run Cells` 執行
- 使用快捷鍵 `Shift` + `Enter` 執行

## 編輯時間
[ProFatXuanAll](https://github.com/ProFatXuanAll) 最後編輯於 *2019/08/06* (yyyy/mm/dd)

In [2]:
import numpy as np

In [13]:
a = np.array([1, 2, 3])

print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[0:2])
print(a[1:])
print(a[:2])
print(a[:])

[1 2 3]
1
2
3
[1 2]
[2 3]
[1 2]
[1 2 3]


In [15]:
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(3,)
int64


In [16]:
print(a + 1)
print(a - 3)
print(a * 2)
print(a / 10)

[2 3 4]
[-2 -1  0]
[2 4 6]
[0.1 0.2 0.3]


In [18]:
print(a + a)
print(a * a)
print(a * np.array([4, 5, 6]))

[2 4 6]
[1 4 9]
[ 4 10 18]


In [9]:
b = np.array([[1, 2, 3],[4, 5, 6]])

print(b)
print(b.shape)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [10]:
print(b[0])
print(b[1])
print(b[0:2])
print(b[1:])
print(b[:2])
print(b[:])

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
